# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-04 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('lv', models.IntegerField(blank=True, default=1)),
                ('exp', models.IntegerField(blank=True, default=0)),
                ('crystal', models.IntegerField(blank=True, default=0)),
                ('gold', models.IntegerField(blank=True, default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
    ]
