# Generated by Django 2.1.5 on 2019-01-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawit', '0002_auto_20190123_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='logstage',
            name='star1_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='logstage',
            name='star2_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='logstage',
            name='types',
            field=models.CharField(choices=[('success', 'success'), ('star1', 'star1'), ('star2', 'star2'), ('fail', 'fail')], default='fail', max_length=20),
        ),
    ]
