# Generated by Django 2.1.5 on 2019-01-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawit', '0003_auto_20190123_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='logstage',
            name='star0_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='logstage',
            name='types',
            field=models.CharField(choices=[('success', 'success'), ('star0', 'star0'), ('star1', 'star1'), ('star2', 'star2'), ('fail', 'fail')], default='fail', max_length=20),
        ),
    ]
