# Generated by Django 2.1.5 on 2019-01-28 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawit', '0004_auto_20190128_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('record', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawit.LogStage')),
            ],
            options={
                'ordering': ('record',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('user_id',),
            },
        ),
        migrations.AddField(
            model_name='bestrecord',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawit.User'),
        ),
    ]
