# Generated by Django 2.1.5 on 2019-01-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawit', '0005_auto_20190128_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestrecord',
            options={'ordering': ('stage_id', 'record')},
        ),
        migrations.RemoveField(
            model_name='bestrecord',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bestrecord',
            name='user',
            field=models.ManyToManyField(to='drawit.User'),
        ),
    ]
