# Generated by Django 2.1.5 on 2019-01-28 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawit', '0006_auto_20190128_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='bestrecord',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='drawit.User'),
        ),
    ]
