# Generated by Django 2.1.5 on 2019-01-28 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawit', '0007_auto_20190128_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestrecord',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='drawit.User', to_field='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
