# Generated by Django 2.1.5 on 2019-01-28 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawit', '0010_auto_20190128_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestrecord',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='drawit.User'),
        ),
    ]
